// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Migrations.Migrations
{
    [DbContext(typeof(BooksContext))]
    [Migration("20210701141836_ChangeBookAndIsbn")]
    partial class ChangeBookAndIsbn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Isbn")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Publisher = "sample pub",
                            Title = "title 1"
                        },
                        new
                        {
                            BookId = 2,
                            Publisher = "sample pub",
                            Title = "title 2"
                        },
                        new
                        {
                            BookId = 3,
                            Publisher = "sample pub",
                            Title = "title 3"
                        },
                        new
                        {
                            BookId = 4,
                            Publisher = "sample pub",
                            Title = "title 4"
                        },
                        new
                        {
                            BookId = 5,
                            Publisher = "sample pub",
                            Title = "title 5"
                        },
                        new
                        {
                            BookId = 6,
                            Publisher = "sample pub",
                            Title = "title 6"
                        },
                        new
                        {
                            BookId = 7,
                            Publisher = "sample pub",
                            Title = "title 7"
                        },
                        new
                        {
                            BookId = 8,
                            Publisher = "sample pub",
                            Title = "title 8"
                        },
                        new
                        {
                            BookId = 9,
                            Publisher = "sample pub",
                            Title = "title 9"
                        },
                        new
                        {
                            BookId = 10,
                            Publisher = "sample pub",
                            Title = "title 10"
                        },
                        new
                        {
                            BookId = 11,
                            Publisher = "sample pub",
                            Title = "title 11"
                        },
                        new
                        {
                            BookId = 12,
                            Publisher = "sample pub",
                            Title = "title 12"
                        },
                        new
                        {
                            BookId = 13,
                            Publisher = "sample pub",
                            Title = "title 13"
                        },
                        new
                        {
                            BookId = 14,
                            Publisher = "sample pub",
                            Title = "title 14"
                        },
                        new
                        {
                            BookId = 15,
                            Publisher = "sample pub",
                            Title = "title 15"
                        },
                        new
                        {
                            BookId = 16,
                            Publisher = "sample pub",
                            Title = "title 16"
                        },
                        new
                        {
                            BookId = 17,
                            Publisher = "sample pub",
                            Title = "title 17"
                        },
                        new
                        {
                            BookId = 18,
                            Publisher = "sample pub",
                            Title = "title 18"
                        },
                        new
                        {
                            BookId = 19,
                            Publisher = "sample pub",
                            Title = "title 19"
                        },
                        new
                        {
                            BookId = 20,
                            Publisher = "sample pub",
                            Title = "title 20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
